// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallTool(arg1, arg2) {
  return window['go']['app']['App']['CallTool'](arg1, arg2);
}

export function ClearTerminalContext(arg1) {
  return window['go']['app']['App']['ClearTerminalContext'](arg1);
}

export function FetchAvailableModels(arg1, arg2) {
  return window['go']['app']['App']['FetchAvailableModels'](arg1, arg2);
}

export function FetchLLMResponse(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['FetchLLMResponse'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetRecentTerminalBuffer(arg1, arg2) {
  return window['go']['app']['App']['GetRecentTerminalBuffer'](arg1, arg2);
}

export function GetRuntimePlatform() {
  return window['go']['app']['App']['GetRuntimePlatform']();
}

export function GetTerminalCwd(arg1) {
  return window['go']['app']['App']['GetTerminalCwd'](arg1);
}

export function GetTools() {
  return window['go']['app']['App']['GetTools']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LoadModel(arg1, arg2, arg3) {
  return window['go']['app']['App']['LoadModel'](arg1, arg2, arg3);
}

export function OpenPermissionSettings() {
  return window['go']['app']['App']['OpenPermissionSettings']();
}

export function ReadActiveTerminalTail(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadActiveTerminalTail'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetActiveTab(arg1) {
  return window['go']['app']['App']['SetActiveTab'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['app']['App']['StartTerminal'](arg1);
}

export function StopLLMResponse() {
  return window['go']['app']['App']['StopLLMResponse']();
}

export function StopTerminal(arg1) {
  return window['go']['app']['App']['StopTerminal'](arg1);
}

export function UpdateMCPSettings(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateMCPSettings'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['app']['App']['WriteToTerminal'](arg1, arg2);
}
