// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';

export function CallTool(arg1:string,arg2:string):Promise<string>;

export function FetchLLMResponse(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:boolean,arg8:Array<any>):Promise<string>;

export function GetTools():Promise<Array<mcp.Tool>>;

export function Greet(arg1:string):Promise<string>;

export function ReadActiveTerminalTail(arg1:number,arg2:number,arg3:number):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetActiveTab(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StopLLMResponse():Promise<void>;

export function StopTerminal(arg1:string):Promise<void>;

export function UpdateMCPSettings(arg1:number,arg2:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
